#Number of orders: 2
#Tasks: kitting
#Number of kitting shipments: 2
#Number of assembly shipments: 0
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: Yes
#Faulty products: Yes
#Sensor blackout: Yes
#Time limit: No

options:
  insert_models_over_bins: true
  insert_models_over_stations: false
  gazebo_state_logging: false
  belt_population_cycles: 0
time_limit: -1

agv_infos:
  agv1:
    location: ks1
  agv2:
  agv2:
    location: as1
    products:
      part_0:
        type: assembly_battery_green
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [pi, 0, pi/2]
  agv3:
    location: as3
    products:
      part_0:
        type: assembly_battery_green
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [pi, 0, pi/2]
  agv4:
    location: ks4    
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    assembly:
      shipment_count: 1
      stations: [as1]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [pi, 0, 0]

  order_1:
    priority: 3
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    assembly:
      shipment_count: 1
      stations: [as3]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [pi, 0, 0]

models_over_bins:
  bin2:
    models:
      assembly_pump_red:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  bin6:
    models:
      assembly_pump_blue:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  bin5:
    models:
      assembly_pump_green:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2  


sensor_blackout:
  product_count: 5
  duration: 30

faulty_products:
  - assembly_sensor_blue_2

